-- 1. What query would you run to get all the customers inside city_id = 312? Your query should return customer first name, last name, email, and address.
select customer.first_name, customer.last_name, customer.email, address.address from customer join address on customer.address_id=address.address_id where address.city_id=312;
-- 2. What query would you run to get all comedy films? Your query should return film title, description, release year, rating, special features, and genre (category).
select film.title, film.description, film.release_year, film.rating, film.special_features, category.name from film join film_category on film.film_id=film_category.film_id join category on film_category.category_id=category.category_id;

-- 3. What query would you run to get all the films joined by actor_id=5? Your query should return the actor id, actor name, film title, description, and release year.
select actor.actor_id, actor.first_name, actor.last_name, film.title, film.description, film.release_year from actor join film_actor on actor.actor_id=film_actor.actor_id join film on film.film_id=film_actor.film_id where actor.actor_id=15;
-- 4. What query would you run to get all the customers in store_id = 1 and inside these cities (1, 42, 312 and 459)? Your query should return customer first name, last name, email, and address.
select c.first_name, c.last_name, c.email, a.address from customer as c join address as a on c.address_id=a.address_id where a.city_id in (1,42,312,459);
-- 5. What query would you run to get all the films with a "rating = G" and "special feature = behind the scenes", joined by actor_id = 15? Your query should return the film title, description, release year, rating, and special feature. Hint: You may use LIKE function in getting the 'behind the scenes' part.
select title, description, release_year, rating, special_features from film where rating = "G" and special_features like "behind the scenes";
-- 6. What query would you run to get all the actors that joined in the film_id = 369? Your query should return the film_id, title, actor_id, and actor_name.
select film.film_id, film.title, actor.actor_id, CONCAT_WS(actor.first_name, actor.last_name) as name from film join film_actor on film_actor.film_id=film.film_id join actor on film_actor.actor_id=actor.actor_id where film.film_id=369;
-- 7. What query would you run to get all drama films with a rental rate of 2.99? Your query should return film title, description, release year, rating, special features, and genre (category).
select film.title, film.description, film.release_year, film.rating, film.special_features, category.name from film join film_category on film.film_id=film_category.film_id join category on film_category.category_id=category.category_id where film.rental_rate=2.99 and category.name="Drama";
-- 8. What query would you run to get all the action films which are joined by SANDRA KILMER? Your query should return film title, description, release year, rating, special features, genre (category), and actor's first name and last name.
select f.title, f.description, f.release_year, f.rating, f.special_features, c.name as category,a.first_name, a.last_name 
from film as f join film_category fc on f.film_id=fc.film_id join category as c on c.category_id=fc.category_id join film_actor as fa on fa.film_id=f.film_id join actor as a on a.actor_id=fa.actor_id where c.name="Drama" and a.first_name="SANDRA" and a.last_name="KILMER";